### PR TITLE
added reset after casting ballot, defaulted to a jetson based EDF

### PR DESCRIPTION
**Pull request by oset-bschuhma**

### CODE REVIEW

**Comment by mattbeattie** [comment]
What happened to the status checks?

**Comment by oset-bschuhma** [comment]
We talked about turning them off yesterday. The branch checks were at 0,and
even reducing the threshold to 0 in karma.config still failed (I. E. 0!>0)

I have to get these changes in by Saturday (or earlier, ideally), so Anne
can test.

Regards,

Bret

**Comment by mattbeattie** [comment]
We talked about turning off the _unit tests_, specifically because zero have been written and they're not adding any value. We did not talk about turning off any other status checks. I believe they still add value.

What I was hoping to see based on that conversation was a disabling of the unit tests in GitHub Actions, with a comment/note/something explaining why and what the plan is to turn them back on.

**Comment by oset-bschuhma** [comment]
I thought you suggested I go into the actions and disable them - maybe I
took it too far. You want me to undo what I did and figure out how to JUST
turn off unit tests?

Regards,

Bret

**Comment by mattbeattie** [comment]
Yes, and please also explain why and what the path is to getting them re-enabled. The configuration for GitHub Actions is here. I've highlighted the test stage.

https://github.com/TrustTheVote-Project/Crossplatform-Ballot-Marking-Device/blob/development/.github/workflows/ci.yml#L29-L31

**Comment by trustthevote** [comment]
OK, will do. Fwiw, I ran all the other checks locally (lint, prettier, e2e)
to make sure they'd pass when I pushed.

Regards,

Bret

**Comment by oset-bschuhma** [comment]
Thanks, I commented out the lines you pointed out and pushed after turning
on workflow actions again.  Everything passed - just need your approval so
I can merge.

I am not sure what you're asking for regarding "why and how" - are you
asking for a plan to implement unit tests so we can reactivate them?  Are
you asking me for a commitment that I'll add X% of tests before I continue
building the app?  This is basically what I was saying a few months ago
when I said I didn't want features to take the back-seat to testing.  We're
at a point where, while I agree that there should be SOME testing, features
MUST be created.  What's a reasonable middle-ground?  Add 2 tests for each
one feature I add so we'll eventually catch up?

Bret

**Review by awoflaherty — APPROVED** [review]

**Comment by mattbeattie** [comment]
I guess I'm asking for "why did the tests need to be disabled?" and "what do we need to do in order to re-enable them?"

In other words, if someone's looking at this and seeing you disable the tests, they're going to wonder why. Without any PR description or explanation in the GitHub Actions code when commenting that out, there's simply no way for them to know.

As an open source project, it's important to explain what you're doing to your stakeholders and fellow software engineers, so that everyone has context for what's going on.

But then again I guess the PR has already merged, so that's that.

**Pull request merged**
